//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminDivision
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Level { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string County { get; set; }
    }
}
