//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillItemDiscount
    {
        public long Id { get; set; }
        public long BillItemId { get; set; }
        public Nullable<long> FavourableSchemeId { get; set; }
        public Nullable<long> FavourableDiscountItemId { get; set; }
    }
}
