//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarHealthEntities : DbContext
    {
        public CarHealthEntities()
            : base("name=CarHealthEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CarType> CarTypes { get; set; }
        public DbSet<CarRepairItem> CarRepairItems { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Vendor> Vendors { get; set; }
        public DbSet<VendorGroup> VendorGroups { get; set; }
        public DbSet<VendorTag> VendorTags { get; set; }
        public DbSet<VendorTagSource> VendorTagSources { get; set; }
    }
}
