//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarType
    {
        public long Id { get; set; }
        public string BrandFirstLetter { get; set; }
        public string BrandName { get; set; }
        public string MfgrName { get; set; }
        public string CarTypeName { get; set; }
        public string CarTypeYear { get; set; }
        public string Specification { get; set; }
        public string BrandCountry { get; set; }
        public string Technology { get; set; }
        public string Grade { get; set; }
        public string GasDisplacement { get; set; }
        public string GearBox { get; set; }
        public System.DateTime RecCreateDt { get; set; }
        public int RecStatus { get; set; }
    }
}
