//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountSchemeItem
    {
        public long Id { get; set; }
        public long SchemeId { get; set; }
        public Nullable<long> ServiceItemId { get; set; }
        public Nullable<long> AccessoryItemId { get; set; }
        public Nullable<int> DiscountType { get; set; }
        public Nullable<int> DiscountRate { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public Nullable<decimal> Member { get; set; }
    }
}
