//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavourableScheme
    {
        public long Id { get; set; }
        public long VendorId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartDt { get; set; }
        public Nullable<System.DateTime> EndDt { get; set; }
        public int CustomerRange { get; set; }
        public string CardTypeIds { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public Nullable<long> DiscountSchemeId { get; set; }
    }
}
