//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCar
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public Nullable<long> CarTypeId { get; set; }
        public string CarNo { get; set; }
        public string FrameNo { get; set; }
        public string EngineNo { get; set; }
        public string LicenseNo { get; set; }
        public Nullable<int> IsDefault { get; set; }
        public System.DateTime RecCreateDt { get; set; }
        public int RecStatus { get; set; }
    }
}
