//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCarRefuel
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public Nullable<System.DateTime> RefuelDt { get; set; }
        public Nullable<int> Mileage { get; set; }
        public string FuelType { get; set; }
        public Nullable<decimal> FuelAmmount { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<int> SurplusMileage { get; set; }
        public Nullable<decimal> SurplusAmmount { get; set; }
        public string StationBrand { get; set; }
        public string RefuelPlace { get; set; }
        public System.DateTime RecCreateDt { get; set; }
        public int RecStatus { get; set; }
    }
}
