//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorComboCardTypeItem
    {
        public long Id { get; set; }
        public long VendorId { get; set; }
        public string Name { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> ProductModelId { get; set; }
        public Nullable<long> ProductCarGradeId { get; set; }
        public Nullable<int> Times { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> RealUnitPrice { get; set; }
        public string Memo { get; set; }
    }
}
