//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorEmployee
    {
        public long Id { get; set; }
        public long VendorId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public string Speciality { get; set; }
        public string Description { get; set; }
        public string Memo { get; set; }
        public string Level { get; set; }
    }
}
