//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorCardLog
    {
        public long Id { get; set; }
        public long CardId { get; set; }
        public string CarNo { get; set; }
        public Nullable<long> BillItemId { get; set; }
        public int Type { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<int> Credits { get; set; }
        public Nullable<System.DateTime> LogDt { get; set; }
        public string Memo { get; set; }
        public Nullable<long> RechargePattern { get; set; }
    }
}
