//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorCardType
    {
        public long Id { get; set; }
        public long VendorId { get; set; }
        public string Name { get; set; }
        public int IsRechargable { get; set; }
        public string RechargeRate { get; set; }
        public int IsDiscountable { get; set; }
        public Nullable<long> DiscountSchemeId { get; set; }
        public Nullable<long> NextCardTypeId { get; set; }
        public Nullable<int> NextCardTypeCredits { get; set; }
        public Nullable<int> IsOnlineSelfService { get; set; }
        public string Description { get; set; }
    }
}
