//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorProductCarGradeItem
    {
        public long Id { get; set; }
        public long VendorId { get; set; }
        public Nullable<long> VendorCarGradeItemId { get; set; }
        public long VendorProductCarGradeId { get; set; }
        public int IsDefault { get; set; }
        public Nullable<int> UpPriceType { get; set; }
        public Nullable<decimal> UpPriceAmmount { get; set; }
        public Nullable<int> UpPriceRate { get; set; }
        public string Memo { get; set; }
        public System.DateTime RecCreateDt { get; set; }
        public int RecStatus { get; set; }
    }
}
