//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorOrder
    {
        public long Id { get; set; }
        public string OrderNo { get; set; }
        public long VendorId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCellphone { get; set; }
        public string CustomCarNo { get; set; }
        public Nullable<System.DateTime> OrderDt { get; set; }
        public string Memo { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> DiscountedPrice { get; set; }
        public int Status { get; set; }
        public System.DateTime RecCreateDt { get; set; }
        public int RecStatus { get; set; }
    }
}
