//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorBill
    {
        public long Id { get; set; }
        public long VendorId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<long> VendorCardId { get; set; }
        public Nullable<long> FavourableSchemeId { get; set; }
        public System.DateTime BillDt { get; set; }
        public Nullable<long> PayPattern { get; set; }
        public int Status { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> RealCost { get; set; }
        public Nullable<int> IsDiscount { get; set; }
        public Nullable<int> IsManualDiscount { get; set; }
        public Nullable<decimal> ManualDiscountAmmount { get; set; }
        public string Memo { get; set; }
        public System.DateTime RecCreateDt { get; set; }
        public int RecStatus { get; set; }
    }
}
