//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorComboCard
    {
        public long Id { get; set; }
        public long VendorId { get; set; }
        public long TypeId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCellphone { get; set; }
        public string CardNo { get; set; }
        public Nullable<System.DateTime> IssueDt { get; set; }
        public Nullable<System.DateTime> LatestUseDt { get; set; }
        public Nullable<System.DateTime> CancelDt { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime RecCreateDt { get; set; }
        public int RecStatus { get; set; }
    }
}
