//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorProductCatalog
    {
        public long Id { get; set; }
        public long VendorId { get; set; }
        public string Name { get; set; }
        public int IsLeaf { get; set; }
        public int Type { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string Memo { get; set; }
        public Nullable<long> SysCatalogId { get; set; }
        public Nullable<int> CanDiscount { get; set; }
        public Nullable<int> IsShowOnApp { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public System.DateTime RecCreate { get; set; }
        public int RecStatus { get; set; }
    }
}
