//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WashingCardType
    {
        public long Id { get; set; }
        public long VendorId { get; set; }
        public string Name { get; set; }
        public int Times { get; set; }
        public decimal Money { get; set; }
        public int IsCardNoLimit { get; set; }
        public Nullable<int> CardNoLimitCount { get; set; }
        public int IsExpireLimt { get; set; }
        public Nullable<int> YearExpireLimit { get; set; }
        public Nullable<int> MonthExpireLimit { get; set; }
        public string Memo { get; set; }
    }
}
